; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-p4-evboard]
platform = espressif32
board = esp32-p4-evboard
framework = arduino
lib_deps = 
	https://github.com/lovyan03/LovyanGFX.git#1.2.19
	https://github.com/mmMicky/TouchLib.git#ccaedcd
build_flags = 
	-DTOUCH_MODULES_GT911
monitor_speed = 115200
